# Site settings
title: FAM Rashel
header-img: img/home-bg.jpg
email: aduh_fam@yahoo.com
copyright_name: FAM
description: "Projects, travels, musics, anything else"
baseurl: ""
url: ""
twitter_username: famrashel
github_username:  famrashel
facebook_username:  fam.rashel.scala
email_username:  aduh_fam@yahoo.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

# Collections
collections:
  projects:
    output: true